services:
  mysql:
    image: mysql:latest
    container_name: 'ecommerce-mysql'
    restart: 'unless-stopped'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  django-app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: 'ecommerce-django'
    restart: 'unless-stopped'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}

volumes:
  mysql-data:
