# Generated by Django 5.0.3 on 2024-03-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_updated_at_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_at',
        ),
    ]
